--- #YAML:1.0
name:    tie-proxy-changes
version: 0.2
generated_by: Marc Lucksch
abstract: Track changes in multilevel structures automatically
license: mit
author:              
  - Marc Lucksch <perl@marc-s.de>
distribution_type: module
requires:
    perl:                5.6     
    Carp:                0
    Scalar::Util:        0
    overload:            0
build_requires:
    Test::More:          0
    Test::NoWarnings:    0
    Test::YAML::Meta:    0
provides:
   Tie::Proxy::Changes:
     file:    lib/Tie/Proxy/Changes.pm
     version: 0.2
meta-spec:
   version: 1.4
   url: http://module-build.sourceforge.net/META-spec-v1.4.html
